spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ip:3306/learn_demo
    username: root
    password: 123456
    hikari:
      #池中连接最长生命周期
      max-lifetime: 1800000
      #控制连接池空闲连接的最小数量
      minimum-idle: 10
      #池中最大连接数
      maximum-pool-size: 10
      #连接允许在池中闲置的最长时间
      idle-timeout: 600000
  jpa:
    show-sql: true
    #建议false。开启Open-EntityManager-in-view，会使数据库租用连接时长变长，长时间占用连接直接影响整体事务吞吐量。然后一不小心就会陷进Session缓存的坑里。
    open-in-view: false
logging:
  level:
    root: WARN
    org:
      example: DEBUG